version: '2'
services:
    controldiners-app:
        image: controldiners
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://controldiners-mysql:3306/controldiners?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    controldiners-mysql:
        extends:
            file: mysql.yml
            service: controldiners-mysql
